name: Workflow2 for Pull and run
on:
  workflow_run:
    workflows: ["Workflow1 for build and push"]
    types: 
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOC_USERNAME }}
        password: ${{ secrets.DOC_PASSWORD }}
    - name: Install SSH
      run: sudo apt-get install -y openssh-client
    - name: Run commands on EC2
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no ec2-user@43.205.235.43 << EOF
        sudo su
        docker pull ${{ secrets.DOC_USERNAME }}/nager:g1
        docker run -p 8080:80 -d ${{ secrets.DOC_USERNAME }}/nager:g1
        EOF
